packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Auth
  "@better-auth/cli": 1.4.0-beta.9
  "@better-auth/expo": 1.4.0-beta.9
  better-auth: 1.4.0-beta.9

  # Build tools
  "@eslint/js": ^9.38.0
  "@vitejs/plugin-react": 5.1.0
  eslint: ^9.38.0
  prettier: ^3.6.2
  typescript: ^5.9.3
  vite: 7.1.12

  # T3 Stack
  "@t3-oss/env-core": ^0.13.8
  "@t3-oss/env-nextjs": ^0.13.8

  # Tailwind
  "@tailwindcss/postcss": ^4.1.16
  "@tailwindcss/vite": ^4.1.16
  tailwindcss: ^4.1.16

  # TanStack / tRPC
  "@tanstack/react-form": ^1.23.8
  "@tanstack/react-query": ^5.90.8
  "@trpc/client": ^11.7.1
  "@trpc/server": ^11.7.1
  "@trpc/tanstack-react-query": ^11.7.1

  # Types
  "@types/node": ^22.18.12

  # UI
  lucide-react: 0.525.0

  # Validation
  zod: ^4.1.12

  # Expo SDK
  expo: ~54.0.20
  expo-constants: ~18.0.10
  expo-dev-client: ~6.0.16
  expo-linking: ~8.0.8
  expo-router: ~6.0.13
  expo-secure-store: ~15.0.7
  expo-splash-screen: ~31.0.10
  expo-status-bar: ~3.0.8
  expo-system-ui: ~6.0.8
  expo-web-browser: ~15.0.8

  # React Native
  react-native: ~0.81.5
  react-native-css: 3.0.1
  react-native-gesture-handler: ~2.28.0
  react-native-reanimated: ~4.1.3
  react-native-safe-area-context: ~5.6.1
  react-native-screens: ~4.16.0
  react-native-worklets: ~0.5.1
  nativewind: 5.0.0-preview.2

  # React Native UI
  "@legendapp/list": ^2.0.14

catalogs:
  react19:
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0
    react: 19.1.4
    react-dom: 19.1.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  lightningcss: 1.30.1
  vite: 7.1.12

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
